### ISSUE TITLE
import error for specific module

### ISSUE THREAD

**Issue by ganglio33** [squeaky-pl/portable-pypy#59]
Hi many thanks for this version. I have installed portable-pypy as indicated and created a virtual environment with the suggested command. I have then installed all my packages, among them flask, in the virtual environment.

I then have the following problem:

```
(pypyenv) simon@simon-VirtualBox:~/repos/XXXXXX$ python3 
Python 3.5.3 (a37ecfe5f142bc971a86d17305cc5d1d70abec64, Jun 08 2017, 19:43:54)
[PyPy 5.8.0-beta0 with GCC 6.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
And now for something completely different: ``RPython magically makes you rich
and famous (says so on the tin)''
>>>> from flask import Flask
>>>> exit()
```

As you can see, I don't have any problems importing Flask. Now the same with pypy

```
(pypyenv) simon@simon-VirtualBox:~/repos/XXXXXX$ ~/pypy3.5-portable/bin/pypy3.5
Python 3.5.3 (a37ecfe5f142bc971a86d17305cc5d1d70abec64, Jun 08 2017, 19:43:54)
[PyPy 5.8.0-beta0 with GCC 6.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
And now for something completely different: ``PyPy and CPython: they are mortal
enemies intent on killing each other''
>>>> from flask import Flask
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'flask'

```

Is this a bug of pypy or am I doing something completely wrong?

**Comment by squeaky-pl** [comment]
You are confused with how virtualenv works, in both cases you are running PyPy. When you type `python3` in virtualenv (pypyenv) in your prompt it goes to pypy binary inside virtualenv (try `which python3`) to confirm that. When you put the path explicitly `~/pypy3.5-portable/bin/pypy3.5` you run PyPy __outside__ virtualenv even though you see (pypyenv) in the shell. It's because virtualenv modifies your `PATH`. In other words when you use virtualenv it crates a copy of you PyPy directory and you clearly installed your packages in that copy.

**Comment by ganglio33** [comment]
Thanks a lot for your answer. Now that it works (at least locally) I have about 6X speed increase :D You're the best!
