### ISSUE TITLE
Would you be interested in providing an AppImage?

### ISSUE THREAD

**Issue by probonopd** [squeaky-pl/portable-pypy#75]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

In the case of portable-pypy, the already-existing binaries built on CentOS 6 could be put into an AppImage rather easily.

**Comment by squeaky-pl** [comment]
I dont think this brings much value since Portable PyPy already works on those distributions, no root needed, no system library changes needed and probably it doesnt need any desktop integration. This possibly puts me into a position of supporting another technology I don't use myself. If somebody else wants and is willing to commit to maintaining it then fine but I dont see me doing it myself.
